"""Keep pytest-owned runtime artifacts outside the repository worktree.

The elevated Codex sandbox runs commands as a dedicated Windows account while
preserving the interactive user's ``USERNAME`` environment variable. Pytest
uses that inherited value for its shared ``pytest-of-<user>`` directory, so a
terminal run and a sandboxed run can otherwise collide on a directory whose ACL
belongs to a different Windows identity.

This root conftest is loaded before pytest configures its tmp-path and cache
plugins. It gives each *effective* Windows account a separate system-temp root
without forcing one fixed ``--basetemp`` (which would be unsafe for concurrent
pytest sessions). Explicit caller overrides remain authoritative.
"""

from __future__ import annotations

import sys

# Set this while the root conftest is still executing: importlib checks the flag
# before caching this module, and all later test imports inherit it. Pytest runs
# therefore do not scatter ignored __pycache__ directories through the worktree.
sys.dont_write_bytecode = True

import getpass
import hashlib
import os
from pathlib import Path
import re
import tempfile


_UNSAFE_PATH_CHARS = re.compile(r"[^A-Za-z0-9_.-]")
_ROOT_PYCACHE = Path(__file__).with_name("__pycache__")


def _effective_user_key() -> str:
    """Return a short stable key for the account running this process."""

    try:
        # Unlike getpass.getuser(), os.getlogin() is not derived from the
        # inherited USERNAME value in the native Windows Codex sandbox.
        username = os.getlogin()
    except OSError:
        # CI and detached terminals may not have a login session. Their normal
        # environment-derived identity remains the best available partition.
        username = getpass.getuser()
    sanitized = _UNSAFE_PATH_CHARS.sub("_", username).strip(".") or "unknown"
    # Deep manual-validation fixtures enforce a 240 UTF-16-unit path budget.
    # Hashing keeps the identity partition stable without spending that budget
    # on a potentially long account name or exposing it in diagnostic paths.
    return hashlib.sha256(sanitized.casefold().encode("utf-8")).hexdigest()[:8]


def _default_pytest_artifact_root() -> Path:
    """Build the per-effective-user pytest root under the system temp folder."""

    return (
        Path(tempfile.gettempdir())
        / "om"
        / _effective_user_key()
    )


_artifact_root = Path(
    os.environ.setdefault(
        "PYTEST_DEBUG_TEMPROOT",
        str(_default_pytest_artifact_root()),
    )
)
# Pytest creates ``pytest-of-<user>`` with ``parents=False`` beneath a custom
# PYTEST_DEBUG_TEMPROOT, so the exact identity partition must exist first.
_artifact_root.mkdir(mode=0o700, parents=True, exist_ok=True)
os.environ.setdefault("PYTEST_CACHE_DIR", str(_artifact_root / "cache"))


def _remove_root_conftest_bytecode(cache_dir: Path = _ROOT_PYCACHE) -> None:
    """Remove only this scaffold's generated bytecode and an empty cache dir."""

    if not cache_dir.is_dir():
        return
    # The interpreter can emit the root conftest's own pyc before the module
    # sets dont_write_bytecode. Never broaden cleanup to unrelated cache files.
    for cached_conftest in cache_dir.glob("conftest.*.pyc"):
        cached_conftest.unlink(missing_ok=True)
    try:
        cache_dir.rmdir()
    except OSError:
        # A nonempty directory belongs to another cache producer or concurrent
        # process and must remain untouched.
        pass


def pytest_sessionfinish(session, exitstatus) -> None:  # noqa: ARG001
    """Leave no root-level bytecode artifact after a normal pytest session."""

    _remove_root_conftest_bytecode()
